name: Linux builds
on: push
jobs:

  build_ubuntu_clang_8:
    name: Clang 8 (ubuntu-18.04)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Log environment
        run:  ./scripts/log-env.sh
      - run:  sudo apt update
      - name: Install dependencies
        run:  sudo apt install -y clang-8 $(./scripts/list-build-dependencies.sh -p apt)
      - name: Build
        run:  ./scripts/build.sh --compiler clang --compiler-version 8 --lto
      - name: Summarize warnings
        run:  ./scripts/count-warnings.py build.log

  build_ubuntu_matrix_gcc:
    name: GCC
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04]
    steps:
      - uses: actions/checkout@v1
      - name: Log environment
        run:  ./scripts/log-env.sh
      - run:  sudo apt update
      - name: Install dependencies
        run:  sudo apt install -y $(./scripts/list-build-dependencies.sh -p apt)
      - name: Build
        run:  ./scripts/build.sh
      - name: Summarize warnings
        run:  ./scripts/count-warnings.py build.log

  build_ubuntu_gcc9:
    name: GCC 9 (ubuntu-18.04)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Log environment
        run:  ./scripts/log-env.sh
      - run:  sudo apt update
      - name: Install dependencies
        run:  sudo apt install -y g++-9 $(./scripts/list-build-dependencies.sh -p apt)
      - name: Build
        run:  ./scripts/build.sh --compiler-version 9 --lto
      - name: Summarize warnings
        run:  ./scripts/count-warnings.py build.log
